# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.0
_src_path: git+https://github.com/fmi-faim/ipa-project-template
author: Nessim Louafi
organization: Friedrich Miescher Institute for Biomedical Research
project_name: cohesin_live_cell_analysis
